name: Notify Update

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger RepoB Sync
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/Kyon-H/kyon-h.github.io/dispatches \
        -d '{"event_type":"blog-bak-updated"}'
